"""Candidate findings: the facts worth considering, and their materiality.

This module produces *candidates* — statements that are true of the data, each already
judged for materiality. It does not decide which ones a business owner should be told, nor
does it write the narrative; that judgement belongs to the `bops-sales-intelligence` skill.

Everything here is class 4 (calculated) or class 1 (user data). The single class-5
interpretation the slice emits is generated by the skill, not by this module — which is why
nothing below phrases a cause, only a change.
"""

from decimal import Decimal, ROUND_HALF_UP

from .. import materiality as materiality_mod


def _two_places(value):
    """The one presentation rounding: Decimal, half up, as `analytics.domain` renders (R-16)."""
    return Decimal(value).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def _finding(statement, label, direction=None, verdict=None, basis=None):
    return {
        "statement": statement,
        "label": label,
        "direction": direction,
        "materiality": verdict.outcome if verdict is not None else None,
        "materiality_reason": verdict.reason if verdict is not None else None,
        "basis": basis,
    }


def build(result, currency_formatter):
    """Derive candidate findings from a completed pipeline run."""
    analysis = result.analysis
    findings = []

    # -- revenue trend ------------------------------------------------------
    trend = analysis.get("revenue_trend") or {}
    verdict = analysis.get("revenue_materiality")
    if trend.get("direction"):
        direction = {"rising": "positive", "falling": "negative"}.get(trend["direction"])
        findings.append(_finding(
            "Revenue is %s: %s in the first half of the period versus %s in the second, "
            "a change of %s%%."
            % (trend["direction"], currency_formatter(trend["earlier_total"]),
               currency_formatter(trend["later_total"]), trend["change_pct"]),
            "FACT", direction, verdict,
            basis="sum of mapped revenue by month, compared half over half"))

    if trend.get("peak"):
        peak_period, peak_value = trend["peak"]
        findings.append(_finding(
            "The strongest month was %s at %s." % (peak_period,
                                                   currency_formatter(peak_value)),
            "FACT", None, None, basis="monthly revenue totals"))

    # -- margin -------------------------------------------------------------
    margin_verdict = analysis.get("margin_materiality")
    if margin_verdict is not None and analysis.get("margin_earlier_pct") is not None:
        earlier = analysis["margin_earlier_pct"]
        later = analysis["margin_later_pct"]
        change = later - earlier
        direction = "negative" if change < 0 else "positive"
        findings.append(_finding(
            "Average gross margin moved from %s%% to %s%%, a change of %s "
            "percentage points." % (_two_places(earlier), _two_places(later),
                                    _two_places(change)),
            "FACT", direction, margin_verdict,
            basis="mean of monthly gross margin, compared half over half"))

        series = analysis.get("margin_series") or []
        if len(series) >= 6:
            recent = series[-6:]
            if recent[-1][1] < recent[0][1]:
                findings.append(_finding(
                    "Gross margin has fallen in the most recent six months, from %.2f%% "
                    "in %s to %.2f%% in %s."
                    % (recent[0][1], recent[0][0], recent[-1][1], recent[-1][0]),
                    "FACT", "negative", None,
                    basis="monthly gross margin series, last six periods"))

    # -- products -----------------------------------------------------------
    ranked = analysis.get("product_ranked") or []
    if ranked:
        best = ranked[0]
        findings.append(_finding(
            "%s is the largest product by revenue at %s (%s%% of total)."
            % (best["key"], currency_formatter(best["total"]), best["share_pct"]),
            "FACT", None, None, basis="revenue grouped by mapped product column"))

    for row, verdict in (analysis.get("product_materiality") or []):
        if verdict.outcome != materiality_mod.MATERIAL:
            continue
        direction = "positive" if row["change"] > 0 else "negative"
        findings.append(_finding(
            "%s moved from %s to %s between the two halves of the period (%s)."
            % (row["key"], currency_formatter(row["earlier"]),
               currency_formatter(row["later"]), currency_formatter(row["change"])),
            "FACT", direction, verdict,
            basis="product revenue compared half over half"))

    # -- regions ------------------------------------------------------------
    region_movers = analysis.get("region_movers") or []
    if region_movers:
        strongest = max(region_movers, key=lambda r: r["change"])
        weakest = min(region_movers, key=lambda r: r["change"])
        findings.append(_finding(
            "%s grew most by region, from %s to %s."
            % (strongest["key"], currency_formatter(strongest["earlier"]),
               currency_formatter(strongest["later"])),
            "FACT", "positive", None, basis="regional revenue compared half over half"))
        if weakest["change"] < 0:
            findings.append(_finding(
                "%s declined, from %s to %s."
                % (weakest["key"], currency_formatter(weakest["earlier"]),
                   currency_formatter(weakest["later"])),
                "FACT", "negative", None,
                basis="regional revenue compared half over half"))

    return findings


def undetermined_example(result, config):
    """A materiality verdict that cannot be reached, for honesty about limits.

    Not every question has an answer in the data. A comparison against a prior year that
    the dataset does not cover is `undetermined` — reporting it as "not material" would be
    a quiet lie.
    """
    return materiality_mod.assess_amount(
        "Revenue versus the same period last year",
        (result.kpis.get("revenue").value
         if result.kpis.get("revenue") and result.kpis["revenue"].available else None),
        None, config)
